/**
 * URL для TopoJSON файлов стран.
 * Используем CDN Highcharts как надежный источник.
 */
export const MAP_CONFIG: Record<string, { url: string; center: [number, number]; scale: number }> = {
  ru: {
    url: 'https://code.highcharts.com/mapdata/countries/ru/ru-all.topo.json',
    center: [95, 60],
    scale: 150,
  },
  ua: {
    url: 'https://code.highcharts.com/mapdata/countries/ua/ua-all.topo.json',
    center: [31, 48.5],
    scale: 1200,
  },
  by: {
    url: 'https://code.highcharts.com/mapdata/countries/by/by-all.topo.json',
    center: [28, 53.5],
    scale: 2500,
  },
  cz: {
    url: 'https://code.highcharts.com/mapdata/countries/cz/cz-all.topo.json',
    center: [15.5, 49.8],
    scale: 4000,
  },
};

/**
 * Маппинг имен регионов из data.json в ключи/имена из TopoJSON.
 * Ключ — имя из data.json, значение — hc-key или name из TopoJSON.
 */
export const REGION_MAPPING: Record<string, Record<string, string>> = {
  ru: {
    'Адыгея': 'Adygey',
    'Башкортостан': 'Bashkortostan',
    'Бурятия': 'Buryat',
    'Республика Алтай': 'Gorno-Altay',
    'Дагестан': 'Dagestan',
    'Ингушетия': 'Ingush',
    'Кабардино-Балкария': 'Kabardin-Balkar',
    'Калмыкия': 'Kalmyk',
    'Карачаево-Черкесия': 'Karachay-Cherkess',
    'Карелия': 'Karelia',
    'Республика Коми': 'Komi',
    'Марий Эл': 'Mariy-El',
    'Мордовия': 'Mordovia',
    'Саха (Якутия)': 'Sakha (Yakutia)',
    'Северная Осетия': 'North Ossetia',
    'Татарстан': 'Tatarstan',
    'Тыва': 'Tuva',
    'Удмуртия': 'Udmurt',
    'Хакасия': 'Khakass',
    'Чувашия': 'Chuvash',
    'Алтайский край': 'Altay',
    'Краснодарский край': 'Krasnodar',
    'Красноярский край': 'Krasnoyarsk',
    'Приморский край': 'Primor\'ye',
    'Ставропольский край': 'Stavropol\'',
    'Хабаровский край': 'Khabarovsk',
    'Амурская область': 'Amur',
    'Архангельская область': 'Arkhangel\'sk',
    'Астраханская область': 'Astrakhan\'',
    'Белгородская область': 'Belgorod',
    'Брянская область': 'Bryansk',
    'Владимирская область': 'Vladimir',
    'Волгоградская область': 'Volgograd',
    'Вологодская область': 'Vologda',
    'Воронежская область': 'Voronezh',
    'Ивановская область': 'Ivanovo',
    'Иркутская область': 'Irkutsk',
    'Калининградская область': 'Kaliningrad',
    'Калужская область': 'Kaluga',
    'Камчатский край': 'Kamchatka',
    'Кемеровская область — Кузбасс': 'Kemerovo',
    'Кировская область': 'Kirov',
    'Костромская область': 'Kostroma',
    'Курганская область': 'Kurgan',
    'Курская область': 'Kursk',
    'Ленинградская область': 'Leningrad',
    'Липецкая область': 'Lipetsk',
    'Магаданская область': 'Maga Buryatdan',
    'Московская область': 'Moskovsskaya',
    'Мурманская область': 'Murmansk',
    'Нижегородская область': 'Nizhegorod',
    'Новгородская область': 'Novgorod',
    'Новосибирская область': 'Novosibirsk',
    'Омская область': 'Omsk',
    'Оренбургская область': 'Orenburg',
    'Орловская область': 'Orel',
    'Пензенская область': 'Penza',
    'Пермский край': 'Perm\'',
    'Псковская область': 'Pskov',
    'Ростовская область': 'Rostov',
    'Рязанская область': 'Ryazan\'',
    'Самарская область': 'Samara',
    'Саратовская область': 'Saratov',
    'Сахалинская область': 'Sakhalin',
    'Свердловская область': 'Sverdlovsk',
    'Смоленская область': 'Smolensk',
    'Тамбовская область': 'Tambov',
    'Тверская область': 'Tver\'',
    'Томская область': 'Tomsk',
    'Тульская область': 'Tula',
    'Тюменская область': 'Tyumen\'',
    'Ульяновская область': 'Ul\'yanovsk',
    'Челябинская область': 'Chelyabinsk',
    'Забайкальский край': 'Chita',
    'Ярославская область': 'Yaroslavl\'',
    'Москва': 'Moskva',
    'Санкт-Петербург': 'City of St. Petersburg',
    'Еврейская автономная область': 'Yevrey',
    'Ненецкий автономный округ': 'Nenets',
    'Ханты-Мансийский автономный округ — Югра': 'Khanty-Mansiy',
    'Чукотский автономный округ': 'Chukchi Autonomous Okrug',
    'Ямало-Ненецкий автономный округ': 'Yamal-Nenets',
    'Севастополь': 'Sevastopol', // Может отсутствовать в некоторых картах
    'Республика Крым': 'Crimea', // Может отсутствовать в некоторых картах
    'Чеченская Республика': 'Chechnya',
  },
  ua: {
    'Киев': 'Kyiv',
    'Винницкая область': 'Vinnytsya',
    'Волынская область': 'Volyn',
    'Днепропетровская область': 'Dnipropetrovsk',
    'Донецкая область': 'Donetsk',
    'Киевская область': 'Kyiv City',
    'Житомирская область': 'Zhytomyr',
    'Закарпатская область': 'Transcarpathia',
    'Запорожская область': 'Zaporizhzhya',
    'Ивано-Франковская область': 'Ivano-Frankivsk',
    'Харьковская область': 'Kharkiv',
    'Кировоградская область': 'Kirovohrad',
    'Луганская область': 'Luhansk',
    'Львовская область': 'Lviv',
    'Николаевская область': 'Mykolayiv',
    'Одесская область': 'Odessa',
    'Полтавская область': 'Poltava',
    'Ровенская область': 'Rivne',
    'Сумская область': 'Sumy',
    'Тернопольская область': 'Ternopil',
    'Херсонская область': 'Kherson',
    'Хмельницкая область': 'Khmelnytskyy',
    'Черкасская область': 'Cherkasy',
    'Черниговская область': 'Chernihiv',
    'Черновицкая область': 'Chernivtsi',
    'АР Крым': 'Crimea',
  },
  by: {
    'Брестская область': 'Brest',
    'Витебская область': 'Vitebsk',
    'Гомельская область': 'Gomel',
    'Гродненская область': 'Grodno',
    'Минская область': 'Minsk',
    'Могилевская область': 'Mogilev',
    'Минск': 'Minsk City',
  },
  cz: {
    'Praha': 'Prague',
    'Jihomoravský kraj (Brno)': 'South Moravian',
    'Jihočeský kraj (České Budějovice)': 'South Bohemian',
    'Pardubický kraj (Pardubice)': 'Pardubice',
    'Královéhradecký kraj (Hradec Králové)': 'Hradec Králové',
    'Kraj Vysočina (Jihlava)': 'Vysočina',
    'Karlovarský kraj (Karlovy Vary)': 'Karlovy Vary',
    'Liberecký kraj (Liberec)': 'Liberec',
    'Olomoucký kraj (Olomouc)': 'Olomouc',
    'Plzeňský kraj (Plзеň)': 'Plzeň',
    'Středočeský kraj (Praha-venkov)': 'Central Bohemian',
    'Moravskoslezský kraj (Ostrava)': 'Moravian-Silesian',
    'Ústecký kraj (Ústí nad Labem)': 'Ústí nad Labem',
    'Zlínský kraj (Zlín)': 'Zlín',
  }
};
